CV-Mask-detection/app/__init__.py
from flask import Flask

from app.errors.routes import error_404, error_403, error_401, error_500


def create_app():
    app = Flask(__name__)

    # Retrieve configuration information
    app.config.from_object('app.config.Config')

    # Initialization of blueprints
    from app.main import main_bp

    # Error handlers
    app.register_error_handler(404, error_404)
    app.register_error_handler(403, error_403)
    app.register_error_handler(401, error_401)
    app.register_error_handler(500, error_500)

    app.register_blueprint(main_bp)
    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

CV-Mask-detection/app/main/__init__.py
from flask import Blueprint

main_bp = Blueprint("main", __name__)

import app.main.routes

CV-Mask-detection/app/main/routes.py
from base64 import b64encode
from io import BytesIO

import cv2
import numpy as np
from PIL import Image
from flask import render_template, Response, flash
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from werkzeug.exceptions import abort
from wtforms import FileField, SubmitField
from app.main import main_bp
from app.main.camera import Camera

from source.test_new_images import detect_mask_in_image
from source.video_detector import detect_mask_in_frame


@main_bp.route("/")
def home_page():
    return render_template("home_page.html")


def gen(camera):

    while True:
        frame = camera.get_frame()
        frame_processed = detect_mask_in_frame(frame)
        frame_processed = cv2.imencode('.jpg', frame_processed)[1].tobytes()
        yield (b'--frame\r\n'
               b'Content-Type: image/jpeg\r\n\r\n' + frame_processed + b'\r\n')


@main_bp.route('/video_feed')
def video_feed():
    return Response(gen(
        Camera()
    ),
        mimetype='multipart/x-mixed-replace; boundary=frame')


def allowed_file(filename):
    ext = filename.split(".")[-1]
    is_good = ext in ["jpg", "jpeg", "png"]
    return is_good


@main_bp.route("/image-mask-detector", methods=["GET", "POST"])
def image_mask_detection():
    return render_template("image_detector.html",
                           form=PhotoMaskForm())


@main_bp.route("/image-processing", methods=["POST"])
def image_processing():
    form = PhotoMaskForm()

    if not form.validate_on_submit():
        flash("An error occurred", "danger")
        abort(Response("Error", 400))

    pil_image = Image.open(form.image.data)
    image = cv2.cvtColor(np.array(pil_image), cv2.COLOR_RGB2BGR)
    array_image = detect_mask_in_image(image)
    rgb_image = cv2.cvtColor(array_image, cv2.COLOR_BGR2RGB)
    image_detected = Image.fromarray(rgb_image, 'RGB')

    with BytesIO() as img_io:
        image_detected.save(img_io, 'PNG')
        img_io.seek(0)
        base64img = "data:image/png;base64," + b64encode(img_io.getvalue()).decode('ascii')
        return base64img


# form
class PhotoMaskForm(FlaskForm):
    image = FileField('Choose image:',
                      validators=[
                          FileAllowed(['jpg', 'jpeg', 'png'], 'The allowed extensions are: .jpg, .jpeg and .png')])

    submit = SubmitField('Detect mask')

CV-Mask-detection/app/templates/error.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="container text-center">
        <h1>Error {{error}}</h1>
        <p class="lead">An errror occurred, please try again</p>
        <div class="row mt-5 d-flex justify-content-center">
            <a role="button" class="btn btn-lg btn-outline-info" href="/">Home page</a>
        </div>
    </div>
</div>
{% endblock %}

CV-Mask-detection/app/templates/home_page.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Welcome to the mask detector live</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/stay-safe.jpg"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-6 d-flex justify-content-end">
                <button id="start" onclick="start()" class="btn btn-outline-success"><i class="fa fa-video-camera"
                                                                                        aria-hidden="true"></i> Start
                </button>
            </div>
            <div class="col-6 d-flex justify-content-start">
                <button id="stop" onclick="stop()" class="btn btn-danger active"><i class="fa fa-stop"
                                                                                    aria-hidden="true"></i> Stop
                </button>
            </div>
        </div>
        <hr>
        <div class="row">
            <h4>What is this?</h4>
        </div>
        <div class="row">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people through your
                camera and write a bounding box around faces,
                looking if they were masks or not. This is not for security purpose.</p>
            <p>If you are interested in more details, check this post I wrote!</p>
        </div>
        <div class="row">
            <h4>Who I am</h4>
        </div>
        <div class="row mb-5">
            <p>I'm Galileo Parise, data scientist and matematician, and I've developed what you see during Italy's
                second lockdown in November, in which I had lots of free time. If you are interested in this and ohter
                stories,
                you can follow me on Linkedin and on Medium.
                Hoping to get soon over this situation,
                I hope you all good health:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>please, stay safe and wear a mask</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
$(document).ready(function(){
    $('#image-detector').attr('class', 'nav-item');
    $('#live').attr('class', 'nav-item active');
})

    function stop(){
        $("img").attr("src", "/static/images/stay-safe.jpg");
        $("#stop").attr("class","btn btn-danger active");

        $("#start").attr("class","btn btn-outline-success");
    }
    function start(){
        $("img").attr("src", "{{url_for('main.video_feed')}}");
        $("#start").attr("class","btn btn-success active");

        $("#stop").attr("class","btn btn-outline-danger");
    }

</script>

{% endblock %}

CV-Mask-detection/app/templates/image_detector.html
{% extends "template.html" %}
{% block content %}
<div class="jumbotron">
    <div class="row">
        <div class="col-12">
            <h1>Try the mask detector on custom images</h1>
        </div>
    </div>
</div>
<div class="container">
    <div class="container-fluid">
        <div id="frame_container" class="row">
            <div class="col-12">
                <img src="/static/images/mask.jpg" id="image-preview" style="max-width:600px"
                     class="img-thumbnail img-fluid mx-auto d-block">
            </div>
        </div>
        <div class="row mt-3 mb-5">
            <div class="col-12 d-flex justify-content-center">

                <form enctype="multipart/form-data" id="image-form" method="POST">
                    <div class="row" id="form-row">
                        <div class="col-12">
                            {{ form.csrf_token() }}

                            {{ form.image.label(class="custom-file-label") }}
                            {% if form.image.errors %}
                            <div class="invalid-feedback">
                                {% for error in form.image.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            <div class="custom-file">
                                {{ form.image(class="custom-file-input",
                                id="new-image", onchange="previewImage(event)") }}
                            </div>
                            {% endif %}
                        </div>
                    </div>

                    <div class="row mt-3">
                        <div class="col-12 d-flex justify-content-center">
                            {{ form.submit(class="btn btn-primary", id ="submit", disabled=True)}}
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <hr>
        <div class="row">
            <h4>What is this?</h4>
        </div>
        <div class="row">
            <p>This is a mask detector, an algorithm based on deep neural networks that detects people in images and
                write a bounding box around faces, looking if they were masks or not. This is not for security
                purpose.</p>
            <p>If you are interested in more details, check this post I wrote!</p>
        </div>
        <div class="row">
            <h4>Who I am</h4>
        </div>
        <div class="row mb-5">
            <p>I'm Galileo Parise, data scientist and matematician, and I've developed what you see during Italy's
                second lockdown in November, in which I had lots of free time. If you are interested in this and ohter
                stories,
                you can follow me on Linkedin and on Medium.
                Hoping to get soon over this situation,
                I hope you all good health:</p>
            <p class="d-flex mx-auto lead text-danger"><strong>please, stay safe and wear a mask</strong>.</p>
            <p></p>
        </div>
    </div>
</div>
{% endblock %}
{% block custom_js %}
<script>
var previewImage = function(event) {
    var element_id = "image-preview";
    var preview = document.getElementById(element_id);
    preview.src = URL.createObjectURL(event.target.files[0]);
    preview.style.display = "block";
    $("#submit").prop("disabled",false);
};
$(document).ready(function(){
    $('#live').attr('class', 'nav-item');
    $('#image-detector').attr('class', 'nav-item active');
})
$(function() {
        $("#submit").each(function(index){
            $(this).on('click', function(e) {

                var url = "{{ url_for('main.image_processing') }}";

                // Form data
                var formData = new FormData();

                // Add form data
            $('#image-form').serializeArray().forEach(
                function(item, index) {
                    formData.append(item.name, item.value);
                }
            );
                // Add the files
                var image = $('#new-image')[0].files[0];
                formData.append('image', image);

                // AJAX query to the endpoint for deletion
                $.ajax({
                    type: "POST", // POST HTTP
                    url:  url +'',
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function(response) {

                        $("#image-preview").attr("src", response);
                        $("#submit").replaceWith('<button class="btn btn-success"><i class="fa fa-check-circle" onclick="location.reload()" aria-hidden="true"></i> Done!</button>');
                        $("#form-row").remove();
                    },
                    error: function(response){
                        location.reload();
                        // Redirect to this page
                    }
                });

                return false;
            })
        })
    })
</script>

{% endblock %}

CV-Mask-detection/app/templates/template.html
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

    <title>Mask detector live</title>
    <style>
        .footer-link{ color: inherit; }
        .footer-link:hover{ color: inherit; }
        body {
    margin: 0;
}

.wrapper {
    display: flex;
    flex-direction: column;
    min-height: 100vh;
}

.footer {
    margin-top: auto;
}
    </style>
</head>
<body>
<div class="wrapper">
    <div class="header">

        <!--banner-->
        <div class="header-row bg-danger" id="header-row" style=" overflow:hidden;">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-xs-12">
                        <a class="navbar-brand logo"
                           href="https://actionaid.org/donate">
                            <p class="text-white mx-3 my-1"><small>
                                Please consider donating to <strong>Actionaid</strong> due to the Coronavirus emergency.
                                Click
                                here for
                                more info. Thanks.</small>
                            </p>
                        </a>
                    </div>
                </div>
            </div>
        </div>

        <!--navbar start-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a class="navbar-brand" href="#">Galileo</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                    aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <li class="nav-item active" id="live">
                        <a class="nav-link" href="/">Live detector</a>
                    </li>
                    <li class="nav-item" id="image-detector">
                        <a class="nav-link" href="/image-mask-detector">Image mask detector</a>
                    </li>
                </ul>
            </div>
        </nav>
        <!--navbar end-->
    </div>
    <div class="content">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        {{ message }}
        {% endfor %}
        {% endif %}
        {% endwith %}

        <!--add custom content with inheritance-->
        {% block content %}
        {% endblock %}
    </div>
    <div class="footer">
        <div class="py-4 bg-dark text-white-50">
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <p>You can follow me here:</p>
                        <div class="row">
                            <div class="col-4">
                                <a href="https://www.linkedin.com/in/galileo-parise-34311198/" class="footer-link">
                                    <i class="fa fa-linkedin-square my-auto mx-2" aria-hidden="true"></i> Linkedin
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="#" class="footer-link">
                                    <i class="fa fa-medium mx-2 my-auto" aria-hidden="true"></i>Medium
                                </a>
                            </div>
                            <div class="col-4">
                                <a href="mailto:parise.galileo@gmail.com?subject=Mask%20detector" class="footer-link">
                                    <i class="fa fa-envelope my-auto mx-2" aria-hidden="true"></i> Mail
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- jQuery, Popper.js, and Bootstrap JS -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
        integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
        crossorigin="anonymous"></script>
{% block custom_js %}
{% endblock %}
</body>
</html>